#!/bin/sh

backup_dir="/backup"
today=$(date +'%Y-%m-%d')
time=$(date +'%Y-%m-%d %H:%M')
backup_file="$backup_dir/backup-$today.sql"
backup_logfile="$backup_dir/logs.txt"

if [ ! -f $backup_file ]; then
    pg_dump -U ${POSTGRES_USER} ${POSTGRES_DB} > "$backup_file"
    echo "[$time] $today copy created" >> "$backup_logfile"
else
  echo "[$time] Copy is exists" >> "$backup_logfile"
fi

find "$backup_dir" -type f -name "backup-*" -mtime +30 -exec rm {} \;

