version: '3.3'

services:
  nginx:
    restart: always
    build:
        context: ./nginx
    ports:
      - "80:80"
      - "443:443" 
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    env_file:
      - ./src/.env
    volumes:
      - ./persistentdata/certbot/conf:/etc/letsencrypt
      - ./persistentdata/certbot/www:/var/www/certbot
      - ./persistentdata/static:/var/www/static
      - ./persistentdata/media:/var/www/media
    depends_on:
      - web

  web:
    build: ./src
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./persistentdata/static:/var/www/static
      - ./persistentdata/media:/var/www/media
    env_file:
      - ./src/.env
    depends_on:
      db:
        condition: service_healthy

  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"

  db:
    image: postgres:13.0-alpine
    restart: always
    volumes:
      - ./persistentdata/db:/var/lib/postgresql/data/
      - ./persistentdata/backup:/backup/
      - ./backup_script:/etc/periodic/15min/backup_script
    ports:
      - "5432:5432"
    env_file:
      - ./src/.env
    healthcheck:
      test: pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB
      interval: 10s
      timeout: 10s
      retries: 10

  certbot:
    image: certbot/certbot
    restart: always
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    volumes:
      - ./persistentdata/certbot/conf:/etc/letsencrypt
      - ./persistentdata/certbot/www:/var/www/certbot