version: '3.3'

services:
  nginx:
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile.local
    ports:
      - "80:80"
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    env_file:
      - ./src/.envLocal
    volumes:
      - ./persistentdata/static:/var/www/static
      - ./persistentdata/media:/var/www/media
    depends_on:
      web:
        condition: service_healthy

  web:
    build:
      context: ./src
      dockerfile: Dockerfile.local
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - ./src/.envLocal
    volumes:
      - ./persistentdata/static:/var/www/static
      - ./persistentdata/media:/var/www/media
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent --write-out 'HTTP CODE : %{http_code}\n' http://127.0.0.1:8000/"
      interval: 5s
      timeout: 10s
      retries: 5

  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"

  db:
    image: postgres:13.0-alpine
    volumes:
      - ./persistentdata/db:/var/lib/postgresql/data/
      - ./persistentdata/backup:/backup/
      - ./backup_script:/etc/periodic/15min/backup_script
    ports:
      - "5432:5432"
    env_file:
      - ./src/.envLocal
    healthcheck:
      test: pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB
      interval: 10s
      timeout: 10s
      retries: 10
