version: '3.8'

services:
  web:
    build: ./src
    restart: always
    ports:
      - 8000:8000
    volumes:
      - .:/usr/src/app
    env_file:
      - ./src/.env
    depends_on:
      - db

  db:
    image: postgres:13.0-alpine
    volumes:
      - ./persistentdata/db:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    env_file:
      - ./src/.env

volumes:
  postgres_data:
