version: '3.3'

services:
  nginx:
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile.local
    ports:
      - "80:80"
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    env_file:
      - ./src/.envLocal
    volumes:
      - ./persistentdata/static:/var/www/static
      - ./persistentdata/media:/var/www/media
    depends_on:
      - web

  web:
    build:
      context: ./src
      dockerfile: Dockerfile.local
    restart: always
    ports:
      - 8000:8000
    env_file:
      - ./src/.envLocal
    volumes:
      - ./persistentdata/static:/var/www/static
      - ./persistentdata/media:/var/www/media
    depends_on:
      - db

  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379

  db:
    image: postgres:13.0-alpine
    ports:
      - 5432:5432
    env_file:
      - ./src/.envLocal