version: '3.3'

services:
  web:
    build:
      context: ./src
      dockerfile: Dockerfile.local
    restart: always
    ports:
      - 8000:8000
    env_file:
      - ./src/.envLocal
    depends_on:
      - db

  db:
    image: postgres:13.0-alpine
    ports:
      - 5432:5432
    env_file:
      - ./src/.envLocal