# Generated by Django 4.1.1 on 2022-10-27 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
                ('code', models.IntegerField(verbose_name='Код')),
                ('number_of_attempts', models.PositiveIntegerField(default=0, verbose_name='Использованные попытки')),
            ],
            options={
                'verbose_name': 'Одноразовый код',
                'verbose_name_plural': 'Одноразовые коды',
                'db_table': 'one-time_codes',
            },
        ),
    ]
