# Generated by Django 4.1.1 on 2022-10-27 17:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='code',
            field=models.CharField(max_length=6, validators=[django.core.validators.MinLengthValidator(6)], verbose_name='Код'),
        ),
    ]
