# Generated by Django 4.1.1 on 2022-11-03 13:42

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_code_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название породы')),
            ],
            options={
                'verbose_name': 'Порода',
                'verbose_name_plural': 'Породы',
                'db_table': 'breeds',
            },
        ),
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Кличка собаки')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Аватар')),
                ('hasAvatar', models.BooleanField(verbose_name='Есть ли аватар')),
                ('data_update_avatar', models.DateTimeField(default=datetime.datetime(2022, 11, 3, 16, 42, 39, 537905), verbose_name='Дата обновления аватара')),
                ('gender', models.BooleanField(verbose_name='Пол (0 - ж, 1 - м)')),
                ('birthday', models.DateField(verbose_name='День рождения')),
                ('city', models.CharField(max_length=128, verbose_name='Город')),
                ('owner', models.TextField(verbose_name='Владельцы')),
                ('phone', models.TextField(verbose_name='Номер телефона')),
                ('hide_phone', models.BooleanField(verbose_name='Скрыть номер')),
                ('about', models.TextField(blank=True, null=True, verbose_name='Текст о собаке')),
                ('food', models.TextField(blank=True, null=True, verbose_name='Информация о питании')),
                ('other', models.TextField(blank=True, null=True, verbose_name='Другая информация')),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Аккаунт владельца')),
                ('breed', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.breed', verbose_name='Порода')),
            ],
            options={
                'verbose_name': 'Собака',
                'verbose_name_plural': 'Собаки',
                'db_table': 'dogs',
            },
        ),
    ]
