# Generated by Django 4.1.1 on 2022-11-03 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_breed_dog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='data_update_avatar',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата обновления аватара'),
        ),
    ]
