# Generated by Django 4.1.1 on 2022-11-04 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_hasavatar_dog_has_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dog',
            old_name='data_update_avatar',
            new_name='date_update_avatar',
        ),
    ]
