# Generated by Django 4.1.1 on 2022-11-10 15:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_notification_subscription_blacklist'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author_notification', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='notification',
            name='recipient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipient', to=settings.AUTH_USER_MODEL, verbose_name='Получатель'),
        ),
        migrations.AddField(
            model_name='notification',
            name='state',
            field=models.CharField(choices=[('UNDEFINED', 'UNDEFINED'), ('WAIT', 'WAIT'), ('EXPIRED', 'EXPIRED'), ('ACCEPT', 'ACCEPT'), ('DECLINE', 'DECLINE'), ('LOST', 'LOST')], default='UNDEFINED', max_length=32, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='notification',
            name='text',
            field=models.TextField(null=True, verbose_name='Текст уведомления'),
        ),
    ]
