# Generated by Django 4.1.1 on 2023-06-26 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_notification_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dog',
            name='hide_phone',
        ),
        migrations.RemoveField(
            model_name='dog',
            name='phone',
        ),
        migrations.AddField(
            model_name='user',
            name='hide_phone',
            field=models.BooleanField(default=True, verbose_name='Скрыть номер'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='День рождения'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='city',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Город'),
        ),
    ]
