# Generated by Django 4.1.1 on 2023-06-26 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_dog_hide_phone_remove_dog_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='owner',
            field=models.TextField(blank=True, null=True, verbose_name='Владельцы'),
        ),
    ]
