# Generated by Django 4.1.1 on 2023-07-29 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_dog_date_created_dog_date_deleted_dog_date_edited_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='walk',
            name='user',
        ),
        migrations.AddField(
            model_name='walk',
            name='dog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.dog', verbose_name='Собака'),
        ),
    ]
