# Generated by Django 4.1.1 on 2023-07-31 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_remove_walk_user_walk_dog'),
    ]

    operations = [
        migrations.AddField(
            model_name='walk',
            name='distance',
            field=models.FloatField(blank=True, null=True, verbose_name='Пройденное расстояние'),
        ),
        migrations.AlterField(
            model_name='walk',
            name='finish',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время окончания'),
        ),
        migrations.AlterField(
            model_name='walk',
            name='time',
            field=models.IntegerField(blank=True, null=True, verbose_name='Фактическое время прогулки'),
        ),
    ]
