# Generated by Django 4.1.1 on 2024-01-04 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
        migrations.AlterModelTable(
            name='message',
            table='message',
        ),
    ]
