# Generated by Django 4.1.1 on 2024-02-04 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_message_options_alter_message_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='author_dog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_author_dog', to='api.dog', verbose_name='Собака автора сообщения'),
        ),
        migrations.AddField(
            model_name='message',
            name='destination_dog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_destination_dog', to='api.dog', verbose_name='Собака получателя'),
        ),
    ]
