# Generated by Django 4.1.1 on 2024-02-04 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_remove_message_author_dog_remove_message_destination_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='participants',
            field=models.ManyToManyField(db_table='chat_participant', null=True, related_name='chat_participants', to='api.participant'),
        ),
    ]
